const FOOD_DATA = [
  {
    "name":"Mango",
    "brand":"Hawkers",
    "price":2.99,
    "image":"Mango.jpg"
  },{
    "name":"Banana",
    "brand":"Hawkers",
    "price":4.99,
    "image":"banana.jpg"
  },
  {
    "name":"Jackfruit",
    "brand":"Mcdonald",
    "price":1.49,
    "image":"Jackfruit.jpg"
  },
  {
    "name":"Apple",
    "brand":"Mcdonald",
    "price":2.99,
    "image":"Apple.jpg"
  },
  {
    "name":"Orange",
    "brand":"Ben & Jerry's",
    "price":9.49,
    "image":"Orange.jpg"
  },
  {
    "name":"Lichi",
    "brand":"Hawkers",
    "price":4.49,
    "image":"Lichi.jpg"
  },
  {
    "name":"Chilli",
    "brand":"Dominos",
    "price":17.99,
    "image":"Chilli.jpg"
  },
  {
    "name":"Orange",
    "brand":"Hawkers",
    "price":2.99,
    "image":"Orange.jpg"
  },
  {
    "name":"Apple",
    "brand":"Subway",
    "price":6.99,
    "image":"Apple.jpg"
  }
];